package: yform_spam_protection
version: '1.3.0'
author: Friends Of REDAXO
supportpage: https://github.com/friendsofredaxo/yform_spam_protection
perm: admin[]
requires:
    redaxo: '^5.17'
    packages:
        yform: '>=4,<6'
    php:
        version: '>=8.1'

page:
    hidden: true

pages:
    yform/spam_protection:
        title: 'Spamschutz'
        perm: admin[]
        icon: rex-icon fa-envelope-circle-check
        subpages:
            settings:
                title: 'Einstellungen'
            docs:
                title: 'Dokumentation'
default_config:
    notification_email: ""
    timer: 1
    timer_session: 5
    timer_form: 10
    honeypot: 1
    ip_block: 1
    ip_block_limit: 10
    ip_block_timer: 300
    geo_block: 0
    tld_block: 0
    tld_list: ".ru"
    warning: "Ihre Anfrage wurde als Spam erkannt und nicht zugestellt. Sollte dies irrtümlich passiert sein, wenden Sie sich bitte an den Betreiber der Website."
