package: yform_spam_protection
version: '1.2.6-dev'
author: 'Friends Of REDAXO, Lead: Alexander Walther'
supportpage: https://github.com/friendsofredaxo/yform_spam_protection
perm: admin[]
requires:
    redaxo: '^5.17'
    packages:
        yform: '^4'
    php:
        version: '>=8.1'

page:
    hidden: true

pages:
    yform/spam_protection:
        title: 'Spamschutz'
        perm: admin[]
        icon: rex-icon fa-envelope-circle-check
        subpages:
            settings:
                title: 'Einstellungen'
            docs:
                title: 'Dokumentation'
default_config:
    timer: 5
